Ajout d'un bouton de réinitialisation des couleurs des cours
PapillonApp/Papillon pull request #120
Opened 2024-03-30 14:50 UTC by godetremy

## Checklist d'avant pull request

- [X] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [X] Vous respectez les conventions de codage et de nomage du projet
- [X] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [X] Cette pull request **n'est pas un duplicata** d'une autre
- [X] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [X] Cette pull request doit être fusionnée dans la branche `development` (le cas contraire préciser laquelle)
- [X] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [ ] (à vérifier mais pour moi non) Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [X] Les détails des changements ont été décris ci-dessous
- [X] Cette pull-request n'est pas une **"breaking-change"** (par exemple des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

## Explications des changements
Cette PR apporte l'ajout d'un menu dans l'onglet gestion des matières, afin de pouvoir y réinitialiser les couleurs par défaut des matières. L'action de "randomiser" les couleurs, ainsi que la réinitialisation son inclus dans un menu, et on chacun une confirmation avant d'appliquer les changement.

Elle contient également un petit bug fix concernant la page d'accueil ou la couleurs défini du cours n'était pas la bonne mais celle par défaut.

![IMG_9549](https://github.com/PapillonApp/Papillon/assets/77058107/f38e6deb-4a56-4193-a313-ba88231a26b2)

2024-03-30 15:56 UTC, hermitoff commented
Petite question, est-ce que sa recrée également les matières supprimées dans le menu ou sa réinitialise que les couleurs ?

2024-03-30 17:09 UTC, godetremy commented
> Petite question, est-ce que sa recrée également les matières supprimées dans le menu ou sa réinitialise que les couleurs

Cela ne réinitialise que les couleurs des matières qui sont déjà dans la liste
<hr>
Oups pour l'autre commit, je ne pensais pas que ça le mettrais ici ! 🤡
Du coup voici une 2e PR en une :

## Checklist d'avant pull request
- [x] Vous avez testé de build le projet avec vos modifications et ce build a réussi
- [x] Vous respectez les conventions de codage et de nomage du projet
- [x] Vous utilisez la tabulation pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request n'est pas un duplicata d'une autre
- [x] Cette pull request est prête à être revue (review) et fusionnée (merge)
- [x] Cette pull request doit être fusionnée dans la branche development (le cas contraire préciser laquelle)
- [x] Il n'y a pas de TODO (aka des annotations pour du code manquant) dans vos modifications
- [ ] (à vérifier aussi) Il n'y a pas d'erreurs de langue dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décris ci-dessous
- [x]  Cette pull-request n'est pas une "breaking-change" (par exemple des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

### Explications des changements

Cette PR apporte l'ajout d'une options dans les réglages afin de pouvoir masquer l'onglet note. L'option est activante dans Préférences > Réglages > Désactiver l'onglet note. Lors de la réactivation, une question aléatoire sera posé à l'utilisateur pour confirmer sont choix.
![IMG_9550](https://github.com/PapillonApp/Papillon/assets/77058107/52af667b-12fe-41cc-ab7b-13f3a09a2bb1)
![IMG_9551](https://github.com/PapillonApp/Papillon/assets/77058107/83437b50-5687-4791-bb49-840e5cce6d3b)
![IMG_9552](https://github.com/PapillonApp/Papillon/assets/77058107/f2530e94-f39e-49e4-ab73-0c3bfc7e3a4b)

2024-03-30 17:47 UTC, Sacha338 requested changes

2024-03-30 17:47 UTC, Sacha338 commented on views/GradesScreen.tsx
> +            subtitle='Vos notes sont masqué.'
Vos notes sont masquéES

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/CoursColor.js
> +                    'Voulez-vous vraiment modifier les couleurs ? Cette action est irréverssible.',
Irréversible avec un seul S

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/CoursColor.js
> +                    'Voulez-vous vraiment réinitialiser les couleurs ? Cette action est irréverssible.',
Même chose

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/CoursColor.js
> +                  'Voulez-vous vraiment modifier les couleurs ? Cette action est irréverssible.',
Meme chose

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/CoursColor.js
> +                  'Voulez-vous vraiment réinitialiser les couleurs ? Cette action est irréverssible.',
Meme chose

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/SettingsScreen.tsx
> +        question: 'Combien font 5*5 ?',
"5 x 5" c’est peut être mieux pour l'utilisateur ?

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/SettingsScreen.tsx
> +        'Vos notes seront de nouveau visible dans l\'onglet note. Un redémmarage peut-être requis.',
visibleS

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/SettingsScreen.tsx
> +            Vos notes seront masqué
masquéES

2024-03-30 17:47 UTC, Sacha338 commented on views/Settings/SettingsScreen.tsx
> +            Désactiver l'onglet note
Mets un S à "note" si tu veux rester accorder au reste. (ligne 512 dans GradesScreen)

2024-03-30 21:04 UTC, godetremy reviewed
fix:typo (Ok je sais pas utiliser gh) 🤡

2024-03-31 16:38 UTC, ecnivtwelve approved these changes

2024-03-31 16:38 UTC, merged

2024-03-31 17:23 UTC, maelgangloff commented
Est-ce que les modifications demandées par @Sacha338 ont été effectués avant la fusion ?

Je ne trouve pas de commit depuis les demandes de changement.