Différents fix sur GradesScreen
PapillonApp/Papillon pull request #205
Opened 2024-05-01 15:08 UTC by Vilerio

- [x] Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
- [x] Vous respectez les conventions de codage et de nomage du projet
- [x] Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
- [x] Cette pull request **n'est pas un duplicata** d'une autre
- [x] Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
- [x] Cette pull request doit être fusionnée dans la branche `development` (le cas contraire préciser laquelle)
- [x] Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
- [x] Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
- [x] Les détails des changements ont été décris ci-dessous
- [x] Cette pull-request n'est pas une **"breaking-change"** (par exemple des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)

![Capture d’écran 2024-05-01 à 17 03 27](https://github.com/PapillonApp/Papillon/assets/69359417/dc6678cc-6133-4a53-822e-faddd9e0551a)
![Capture d’écran 2024-05-01 à 17 03 21](https://github.com/PapillonApp/Papillon/assets/69359417/bb6a4fea-c1a3-4a47-8bc9-f605db193951)

Règle ça : https://github.com/PapillonApp/Papillon/issues/203

2024-05-01 15:49 UTC, Sacha338 approved these changes

2024-05-01 19:33 UTC, LeGeek01 requested changes

2024-05-01 19:33 UTC, LeGeek01 commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
alors non ça ça reste, c'est pour le cas où les matières sont trop grandes pour être affichées dans l'encadré des notes

2024-05-01 19:34 UTC, Vilerio commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
De mon côté, les matières trop grandes sont juste coupées puis terminée par "..." dans les encadrés
Et du coup avec ce header, le nom des matières est en double

2024-05-01 20:06 UTC, LeGeek01 commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
le fait qu'il soit en double était voulu dans le cas où la matière était coupé dans l'encadré
donc si tu veux retirer le header tu fais en sorte que le nom de la matière fasse deux lignes dans l'encadré s'il est trop long par exemple

2024-05-01 20:07 UTC, Vilerio commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
Bah on a le début du nom de la matière dans l'encadré, ça suffit pour la reconnaitre, je vois pas de cas ou ça ne suffirait pas

2024-05-01 20:13 UTC, LeGeek01 commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
pour les sous-services

2024-05-01 20:14 UTC, Vilerio commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
hein ?

2024-05-01 20:16 UTC, LeGeek01 commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
Francais > Formatif par exemple
I2D-INGENIER.&DEV.DURAB. > Evaluation Formatives

2024-05-01 20:17 UTC, Vilerio commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
ah oui je vois

2024-05-06 16:41 UTC, Vilerio commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
Je peux avoir un screen de ce que ça donne quand c'est trop long de ton côté stp ?

2024-05-21 19:15 UTC, LeGeek01 commented on views/GradesScreen.tsx
> -            header={formattedCourseName}
Avec un peu de retard, voilà ce que ça donne

![Screenshot_20240521_211348_Papillon.jpg](https://github.com/PapillonApp/Papillon/assets/54872374/e41c6309-a5af-4cdc-add9-ccf073252439)

2024-05-22 17:13 UTC, LeGeek01 approved these changes

2024-05-22 17:14 UTC, merged