[AppBar] Ajout d'un compteur de notification
PapillonApp/Papillon pull request #21
Opened 2024-02-25 18:47 UTC by Yaya-Cout

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] You can **build successfully** the whole project with your changes locally
- [x] You use the coding conventions and the **naming conventions** of the project
- [x] You use **tabs** for indentation
- [x] You make sure that your PR is **not a duplicate**
- [ ] This PR is **ready** to be reviewed and merged
- [x] This PR merges into the **`development`** branch or in the specific branch of the feature you want to merge into
- [x] There is no **`TODO`** in the code
- [x] There is no spelling or grammatical errors in the code
- [x] Details of the issue or feature are documented below
- [x] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Explain changes

J'ai ajouté un compteur de notifications à la barre du bas de l'écran

![Screenshot_20240225-194351](https://github.com/PapillonApp/Renard/assets/67095734/e8a5b623-980a-4b25-b13b-396cf0e0b359)

## Proposed changelog

| Français `fr`                            |
| ---------------------------------------- |
| Ajout d'un compteur de notifications pour les informations |

### Note

Before merging this PR, you will need the approval of at least one of the following people:

- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### Informations supplémentaires

Il manque actuellement la réactivité (lorsqu'une notification est marquée comme lue, même après un rafraichissement du cache).
C'est la première fois que j'utilise du React, donc n'hésitez pas à faire de commentaires si je n'ai pas respecté les conventions du React.

2024-02-25 20:26 UTC, LeGeek01 commented
pour ta fonctionnalité manquante tu devrais exporter ta fonction de badge sur AppCtx pour pouvoir l'appeler dans la vue News, quand on rafraîchis, mais sinon ouais c'est propre bien joué

2024-02-25 20:27 UTC, LeGeek01 commented
aussi je sais pas si tu peux modifier la position du badge, mais si tu peux le décaler un peu plus en haut à gauche

2024-02-25 20:32 UTC, tom-theret commented
On peut désactiver le compteur depuis les paramètres ?

2024-02-25 20:40 UTC, LeGeek01 commented
ah oui pourquoi pas le rajouter ça

2024-02-26 12:07 UTC, Yaya-Cout commented
J'ai déplacé le badge pour ressembler davantage à la [spec de MD3](https://m3.material.io/components/badges/overview).
J'ai aussi réparé le cache des actualités (je ne sais pas pourquoi il était désactivé, mais je pense que ce n'était pas normal), et j'en ai profité pour réparer la réactivité.
Pour le paramètre pour désactiver ça, je le mets dans `Apparence & fonctionnalités` ?
![Screenshot_20240226-130400](https://github.com/PapillonApp/Renard/assets/67095734/3db9d255-23d4-4014-bb63-667b1c2b8628)

2024-02-26 12:43 UTC, LeGeek01 commented
l'icone est mieux comme ça oui, et oui c'est la bonne catégorie dans les paramètres

2024-02-28 09:49 UTC, Yaya-Cout commented
Ah, d'ailleurs, j'ai fait le paramètre pour désactiver le compteur (j'ai oublié d'envoyer un message). Par contre, je ne vois pas comment faire pour l'utiliser sans passer par SyncStorage, vu que je dois lire l'état de manière synchrone dans la fonction. L'autre solution que je vois, ce serait de passer l'atom à 0 pour masquer le compteur, ou d'utiliser un autre atom, mais j'ai peur que ce soit un peu trop bourrin…

2024-02-28 10:53 UTC, tom-theret commented
Je sais pas mais c’est bugé

2024-02-29 17:35 UTC, LeGeek01 commented
je suis en train de build l'appli sur ton code pour vérifier que tout fonctionne

2024-02-29 18:16 UTC, lucas-luchack submitted a review, later dismissed
Cela me semble OK, il faudrait vérifier que le code compile et fonctionne correctement. 
@LeGeek01 reviens vers nous dès que possible.

2024-02-29 19:25 UTC, LeGeek01 commented
mon premier essai a échoué à cause du cache qui s'est très mystérieusement corrompu, ça fais une ~45 minutes que gradle retélécharge tout

2024-03-01 15:23 UTC, LeGeek01 commented
hello cette fois l'appli a bien build, mais le test a échoué (test fait sur l'instance pronote de papillon) :
1. Pas de pastille alors que j'ai bien une news non lue
2. L'appli plante si je vais dans Réglages --> Apparences & fonctionnalités --> Notifications

2024-03-01 15:25 UTC, Yaya-Cout commented
Tu es sur Android ou iOS ? Chez moi ça marche (Android), mais c'est peut-être à cause de mon cache.

2024-03-01 15:26 UTC, LeGeek01 commented
Android sur Samsung Galaxy A13 OneUI 6 (Android 14)
j'ai build l'appli à part entière avec ton code (avec un id différent)

2024-03-01 15:29 UTC, LeGeek01 commented
voilà l'erreur que j'ai
![image](https://github.com/PapillonApp/Renard/assets/54872374/b36b2a5d-a861-4a84-9805-b2a1396a6aaf)

2024-03-01 15:31 UTC, LeGeek01 commented
à mon avis tu dois oublier de créer la variable dans le sync storage au début, qui fait un undefined

2024-03-01 15:31 UTC, Yaya-Cout commented
Oui, je pense que c'est ça. Je n'ai pas du reset l'app en testant après avoir mis le paramètre.

2024-03-01 15:47 UTC, Yaya-Cout commented
Normalement, c'est bon.

2024-03-01 16:16 UTC, LeGeek01 commented
yes cette fois ça fonctionne, seul soucis que je peux relever peut-être c'est la pastille qui disparaît quand on est sur l'onglet actualités, mais sinon c'est bon

2024-03-01 16:18 UTC, Yaya-Cout commented
J'avais masqué intentionnellement la pastille dans l'onglet actualités (notamment car je trouvais ça plus logique de masquer les notifications vu qu'elles sont déjà visibles sur l'écran), mais je peux le remettre assez facilement (il faut juste que je trouve comment reload l'AppBar car le badge ne change pas automatiquement quand je modifie l'atom).

2024-03-01 16:27 UTC, LeGeek01 commented
selon moi c'est mieux de le laisser

2024-03-01 19:34 UTC, LeGeek01 commented
faut essayer sur ios svp

2024-03-01 22:49 UTC, lucas-luchack approved these changes
A tester sur iOS

2024-03-02 15:34 UTC, ecnivtwelve requested changes
La façon dont les changements sont indexés font des appels réguliers à l'API, non ?

2024-03-02 15:54 UTC, tom-theret requested changes
Pas d'option de gestion d'affichage du badge sur iOS (voir [cette vue](https://github.com/PapillonApp/Renard/blob/development/views/Settings/AdjustmentsScreen.tsx) pour faire en sorte d'avoir 1 code pour les 2 systèmes)

2024-03-02 16:27 UTC, LeGeek01 commented
bah tu te doutes bien qu'en tant que dev android on peut pas tout adapter sur ios, donc si quelqu'un peut le faire ce serait pas mal

2024-03-02 16:27 UTC, Vilerio commented
Je peux review IOS mais pas adapter ça

2024-03-02 17:55 UTC, Yaya-Cout commented
> La façon dont les changements sont indexés font des appels réguliers à l'API, non ?

Non, car il y a du cache (et en plus, l'appbar n'est pas souvent refresh).



> Pas d'option de gestion d'affichage du badge sur iOS (voir [cette vue](https://github.com/PapillonApp/Renard/blob/development/views/Settings/AdjustmentsScreen.tsx) pour faire en sorte d'avoir 1 code pour les 2 systèmes)

Je peux essayer, mais je ne pourrais pas tester.

2024-03-12 16:44 UTC, LeGeek01 commented
hello, du neuf par ici ?

2024-03-14 18:01 UTC, Yaya-Cout commented
> hello, du neuf par ici ?

À propos de quoi ?

2024-03-15 09:16 UTC, Vilerio commented
règle les conflits et je test sur IOS

2024-03-24 20:17 UTC, LeGeek01 commented
@Yaya-Cout règle les conflits stp

2024-03-24 20:23 UTC, Yaya-Cout commented
J'ai commencé, mais je dois refaire une partie, vu que le fonctionnement a changé. Je n'ai pas vraiment eu le temps cette semaine (surtout que je suis en même temps sur un autre projet).

2024-03-25 20:09 UTC, chevillardanael commented
Est-ce que je peux avoir un screen du rendu actuel car ce n'est pas passé par figma et ça ne respecte pas trop la charte niveau couleur

2024-04-01 16:04 UTC, tom-theret commented
Je pense que la PR peut être fermé car de nombreuses modifications on était apporté.

2024-04-06 19:18 UTC, closed without merging